Add support for plugins
api-php/boilerplate pull request #36
Opened 2016-12-29 12:26 UTC by Nyholm

This will fix #2

2016-12-29 13:15 UTC, sagikazarmark requested changes

2016-12-29 13:15 UTC, sagikazarmark commented on src/HttpClientConfigurator.php
> +            $this->prependPlugin(new Plugin\AuthenticationPlugin(new Authentication\Bearer($this->apiKey)));
Not sure this is right. What if a logger is in the added plugins? Or we don't care about insanity? Either way, authentication should be the last thing IMO. If someone wants to add custom authentication, don't use the API key. It' vague, but works. (Or use arbitrary authentication option which allows configuring multiple ones)

2016-12-29 13:15 UTC, sagikazarmark commented on src/HttpClientConfigurator.php
> +            $this->prependPlugin(new Plugin\AuthenticationPlugin(new Authentication\Bearer($this->apiKey)));
Also, this preserves state: every call to `createConfiguredClient` will add more and more plugins.

2016-12-29 13:15 UTC, sagikazarmark commented on src/HttpClientConfigurator.php
> +    public function appendPlugin(Plugin $plugin)
Since we are PHP 7, we could use variadic here. Not sure if it's better though, but might make the called methods shorter. WDYT?

2016-12-29 13:15 UTC, sagikazarmark commented on src/HttpClientConfigurator.php
> +    private $plugins;
Maybe initialize the array?

2016-12-29 13:45 UTC, Nyholm commented on src/HttpClientConfigurator.php
> +    private $plugins;
Yes, Thanks!

2016-12-29 13:48 UTC, Nyholm commented on src/HttpClientConfigurator.php
> +            $this->prependPlugin(new Plugin\AuthenticationPlugin(new Authentication\Bearer($this->apiKey)));
Thank you for the feedback. I will update.

We cannot append these plugins either because it will break think when using the CachePlugin.

2016-12-29 13:54 UTC, Nyholm commented on src/HttpClientConfigurator.php
> +    public function appendPlugin(Plugin $plugin)
How would that make things easier?

2016-12-30 04:51 UTC, sagikazarmark commented on src/HttpClientConfigurator.php
> +    public function appendPlugin(Plugin $plugin)
Dunno, just an idea.

2016-12-30 04:51 UTC, sagikazarmark commented on src/HttpClientConfigurator.php
> +    public function appendPlugin(Plugin $plugin)
The way you would call the method can be the same, but you can also pass multiple plugins in one call if you want.

2016-12-30 08:53 UTC, Nyholm commented on src/HttpClientConfigurator.php
> +    public function appendPlugin(Plugin $plugin)
👍

2016-12-30 08:57 UTC, Nyholm commented on tests/HttpClientConfiguratorTest.php
> +        $hcc->prependPlugin($plugin0, $plugin1);
$plugin0 will be the first plugin in the chain.

2016-12-30 14:36 UTC, sagikazarmark commented on tests/HttpClientConfiguratorTest.php
> +        $plugins = NSA::getProperty($hcc, 'prependPlugins');
The NSA is already in PHP source code????

2016-12-30 14:42 UTC, sagikazarmark approved these changes

2016-12-30 14:42 UTC, merged